spring:
  application:
    name: api-gateway
  rabbitmq:
    host: 192.168.3.113
    port: 5672
    username: guest
    password: guest
    
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:

management:
  endpoints:
    web:
      exposure:
        include: routes
