spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mmall
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  rabbitmq:
    host: 192.168.3.113
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.3.113
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
debug: true
env: dev1
